### ISSUE TITLE
 SavedModel file does not exist at...

### ISSUE THREAD

**Issue by mrdotqiang** [tanjeffreyz/auto-maple#107]

**Comment by mrdotqiang** [comment]
![image](https://user-images.githubusercontent.com/99530665/171988271-603aecf4-3f13-4116-8b61-b9261e6d5dca.png)

any suggestion for me? sir

**Comment by mrdotqiang** [comment]
answer me plzzz?

**Comment by heoluvh** [comment]
Download the [TensorFlow model](https://drive.google.com/drive/folders/1SPdTNF4KZczoWyWTgfyTBRvLvy7WSGpu?usp=sharing) and unzip the "models" folder into Auto Maple's "assets" directory.

**Comment by mrdotqiang** [comment]
酸Q

**Comment by mrdotqiang** [comment]
@heoluvh   sir, i just stuck here,  any ideas?
![image](https://user-images.githubusercontent.com/99530665/171991029-640e911d-5e0e-46e4-8533-97eb07e6675e.png)

**Comment by mrdotqiang** [comment]
> Download the [TensorFlow model](https://drive.google.com/drive/folders/1SPdTNF4KZczoWyWTgfyTBRvLvy7WSGpu?usp=sharing) and unzip the "models" folder into Auto Maple's "assets" directory.

![image](https://user-images.githubusercontent.com/99530665/171991081-4cb8eddf-3db6-4e0a-8b3b-542d346010c0.png)

**Comment by mrdotqiang** [comment]
Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found

**Comment by mrdotqiang** [comment]
@heoluvh

**Comment by mrdotqiang** [comment]
![image](https://user-images.githubusercontent.com/99530665/171996372-a396b64d-8751-437c-a9de-dc33de34b724.png)
i guess ive already download tensorflow

**Comment by takimc** [comment]
You should first read the program description and error messages before asking questions.

**Comment by mrdotqiang** [comment]
> You should first read the program description and error messages before asking questions.

yah, i know that.  i run python -m pip install -r requirements.txt  but nothing error

**Comment by mrdotqiang** [comment]
maybe i lack the knowledge of
