### ISSUE TITLE
-

### ISSUE THREAD

**Issue by unknowinglyknown** [tanjeffreyz/auto-maple#111]

**Comment by Ayuei** [comment]
I'm currently making a dataset right now. Would you be interested in helping label?

**Comment by JonathanMedinaRivera** [comment]
I would contact me on discord Walfy#6278

**Comment by liligit012** [comment]
I got some with rotation arrows lol

**Comment by Ayuei** [comment]
> I got some with rotation arrows lol

I think rotation arrows in the dataset is useful actually. They're distinct enough from the regular arrows you can classify them as a rotation arrow. 

It isn't probably isn't possible to classify the rotation itself (without a major rework) but we can just randomly guess it. A 1/8 chance of succeeding is pretty good, assuming we can trivially classify the normal arrows and the rotation arrows.

**Comment by 0rka** [comment]
I'd like to provide some training data as well, hit me up on Discord 0rka#2851
