### ISSUE TITLE
Unable to detect minimap

### ISSUE THREAD

**Issue by RodrigoFreitas-L** [tanjeffreyz/auto-maple#145]
Everything went smooth to build auto maple, the problem is... it doesnt detect minimap
If its of any help, here what it looks like: https://prnt.sc/rWfOxSus6YRT

# I'll be closing it, found the solution, on capture.py I changed the FindWindow string since I'm trying to use it on a private server and it worked.

**Comment by parkjunhoon** [comment]
Hello friends, I also faced the same problem, can you explain the solution in a little more detail?

**Comment by zhyonc** [comment]
> Hello friends, I also faced the same problem, can you explain the solution in a little more detail?

Open capture.py and set FindWindowW second arg is private server name(e.g.goms)
```pyton
#handle = user32.FindWindowW(None, 'MapleStory')
handle = user32.FindWindowW(None, 'goms')
```
