### ISSUE TITLE
rune problem

### ISSUE THREAD

**Issue by xhl9000** [tanjeffreyz/auto-maple#148]
anyone know a fix to this issue?
<img width="182" alt="Screenshot 2022-12-08 135516" src="https://user-images.githubusercontent.com/87189522/206368573-48b6a2d2-2f08-4ea7-a081-3f24381ab760.png">

**Comment by Removelol** [comment]
feel free to let me know if u solved it, it just walks to rune and tries to solve it but always failing

**Comment by xhl9000** [comment]
it works 80 percent of the time if  u play in the smallest resolution

> feel free to let me know if u solved it, it just walks to rune and tries to solve it but always failing
