### ISSUE TITLE
Can I find the training code and dataset for RNN detector?

### ISSUE THREAD

**Issue by jinningli** [tanjeffreyz/auto-maple#165]
I'm curious why RNN is used instead of CNN.

**Comment by Jai-wei** [comment]
The author should be using the faster_rcnn algorithm, as can be seen from his `pipeline.config` file. In fact, cnn should be able to, but the accuracy may not be high. I am going to do it again with yolov5/8.

**Comment by LilCheetos** [comment]
> The author should be using the faster_rcnn algorithm, as can be seen from his `pipeline.config` file. In fact, cnn should be able to, but the accuracy may not be high. I am going to do it again with yolov5/8.

Hi, did u found a way to replace it with yolov5?

**Comment by hxypqr** [comment]
@Jai-wei 想问下用yolo的话效果怎么样
