### ISSUE TITLE
help for starters

### ISSUE THREAD

**Issue by yehoshuaab** [tanjeffreyz/auto-maple#168]
i followed all the steps but got stuck in step 6 if anyone can help me i would glad

**Comment by tanjeffreyz** [comment]
Sorry about that, should be resolved with Wetdragon's latest changes

**Comment by yehoshuaab** [comment]
what is Wetdragon's latest patch?

**Comment by tanjeffreyz** [comment]
It should be updated now: https://github.com/tanjeffreyz/auto-maple/releases

**Comment by yehoshuaab** [comment]
https://imgur.com/a/5bGYqfM
when i run the "python -m pip install -r requirements.txt" its say python is not recognized and yes i download python 3
