### ISSUE TITLE
Chat GPT API to solve white room queries?

### ISSUE THREAD

**Issue by loopedice** [tanjeffreyz/auto-maple#187]
I thought of this the other day and realized using Chat GPT (prompted to give concise small answers), and then split the result into separate sentences in game could give a very real illusion that a real player is there. Have yall giving thoughts into incorporating this?

**Comment by hxypqr** [comment]
It's difficult, this involves OCR technology, NER technology, and using NER to extract entities to match the entities with the NPCs or monsters in each map

**Comment by hxypqr** [comment]
It's difficult, this involves OCR, NER, and using NER to extract entities to match the entities with the NPCs or monsters in each map
