### ISSUE TITLE
HSV color ranges for detecting buddy/guild users on minimap

### ISSUE THREAD

**Issue by jae0224** [tanjeffreyz/auto-maple#190]
Is there anyone familiar with the notifier code specifically notifying feature for sounding a ding on random players entering the map. 

Trying to do the same for guild/buddy icons but can't seem to find the right HSV ranges to make it work. 

Image of the ranges for the red dot (random players)

![image](https://github.com/tanjeffreyz/auto-maple/assets/36830011/30cc2f1f-f22f-49f2-a081-dfa8cac6851a)

**Comment by ElfenSterben** [comment]
why you not find a guild/buddy in a same map and screenshot the mini map, convert it to hsv, then you can get the hsv ranges for guild/buddy

**Comment by jae0224** [comment]
I've been able to get the hsv value of the guild/buddy dot color but no luck on getting the correct ranges. Everything i've tried so far, it doesn't detect the minimap icon, it just keeps giving a false positive. 

> why don't you find a guild/buddy in a same map and screenshot the mini map, convert it to hsv, then you can get the hsv ranges for guild/buddy

**Comment by ElfenSterben** [comment]
you cloud write a smallest program, only run the code with capture with minimap, display the minimap with opencv, and debug it

**Comment by jae0224** [comment]
yeah it's solved
