### ISSUE TITLE
Rune not work

### ISSUE THREAD

**Issue by ivanchan5209** [tanjeffreyz/auto-maple#56]
Hi all, the rune solve is not worked for me.
Do you guys have the same problem?
The command prompt only prints the string "Solving rune" and without solving the rune

**Comment by heoluvh** [comment]
![image](https://user-images.githubusercontent.com/67316188/165909078-f6bcb9a9-a912-4ca7-9ceb-fcf90af5c02f.png)
default is Y key to solve rune
you can replace it with any button you want

**Comment by ivanchan5209** [comment]
Hi tanjeffreyz,

I already set 1920 x 1080 in config.py. It still does not work
This is my screen capture
![image](https://user-images.githubusercontent.com/44666088/166961650-0904921f-dce9-4300-af27-1f2f7972d3de.png)

**Comment by ivanchan5209** [comment]
Oh~ I did it. It work only 1366 x 768
