### ISSUE TITLE
run with GPU

### ISSUE THREAD

**Issue by fuqi1001** [tanjeffreyz/auto-maple#59]
After using this nearly 8 month, i just found i'm using the cpu to run the Tensorflow! 🤣 Seems thats why each rune solve cost nearly 20s and sometime even failed.

I have change the my graphic card from 1060 to AMD yes, so i think i can not directly use the `tensorflow-gpu` package, kind curiosity does the model can running with `tensorflow-directml`. Sorry i have 0 knowledge about ML.

**Comment by tanjeffreyz** [comment]
Hi, unfortunately Tensorflow DirectML isn't supported for Python 3.8 or newer, which may conflict with some of Auto Maple's dependencies. I'm working on a much lighter weight arrow detection model in PyTorch, which should be much faster than the current model (even on CPU).

**Comment by fuqi1001** [comment]
Got it, thank you so much! Will keep eye on the update 🕶️

**Comment by fuqi1001** [comment]
by the way, do you have any group chat or any contact info regarding this project

**Comment by tanjeffreyz** [comment]
Ah sorry, I don't have any group chat set up. I'll always be available on GitHub though, if you have any questions!
