### ISSUE TITLE
keybind in kanna.py

### ISSUE THREAD

**Issue by yuiiaaz** [tanjeffreyz/auto-maple#62]
sorry to trouble u again! but what bind is this for E? looks like movement bind to me or is it a skill?

    def main(self):
        num_presses = 3
        time.sleep(0.05)
        if self.direction in ['up', 'down']:
            num_presses = 2
        if self.direction != 'up':
            key_down(self.direction)
            time.sleep(0.05)
        if self.jump:
            if self.direction == 'down':
                press('space', 3, down_time=0.1)
            else:
                press('space', 1)
        if self.direction == 'up':
            key_down(self.direction)
            time.sleep(0.05)
        press('e', num_presses)
        key_up(self.direction)
        if settings.record_layout:
            config.layout.add(*config.player_pos)

**Comment by tanjeffreyz** [comment]
Hi, sorry for the confusion, the [newest release](https://github.com/tanjeffreyz/auto-maple/releases/tag/v2.1.1) should have all the key bindings at the top for more clarity!
