### ISSUE TITLE
Rune Solving Problem

### ISSUE THREAD

**Issue by Anxiot** [tanjeffreyz/auto-maple#64]
auto-maple is able to solve runes initially but when the arrows turn orange, blueish, the rune solver gets stuck on 
`Solving rune:`

and the program loops on solving runes.

I see that the problem has been brought up before. Has it already been resolved or am i missing something?
Appreciate any advice on this. Thanks!

**Comment by tanjeffreyz** [comment]
Hi, sorry about that, unfortunately the current rune solver is doesn't work on the blueish and spinning arrows.

**Comment by heoluvh** [comment]
am too

**Comment by takimc** [comment]
Hello. I know the solution for the blue runes.
However, I am not familiar with Github and do not know how to publish an improved version of someone else's code. Also, there are methods that are accurate but not machine-learned and will not work in the future.
If you still want to know, I can tell you how to solve this problem on Discord.

**Comment by heoluvh** [comment]
> Hello. I know the solution for the blue runes. However, I am not familiar with Github and do not know how to publish an improved version of someone else's code. Also, there are methods that are accurate but not machine-learned and will not work in the future. If you still want to know, I can tell you how to solve this problem on Discord.

boydcbn#2309 please show me how to fix it
  it
