### ISSUE TITLE
Check if arrive at next Routine coordinate

### ISSUE THREAD

**Issue by cheezeburger** [tanjeffreyz/auto-maple#67]
Hi, how can I check if the character has arrived at the next point? I want to let it attack infinitely until it has reached the next point and call config.routine.step()

**Comment by tanjeffreyz** [comment]
Hi, at the moment the routine/command functionality is pretty limited. For a flash jump class, you could add an attack after each flash jump (attack in the Move command) so it attacks while moving to the next point. For teleport classes, unfortunately you'd have a bunch of Points + attacks along the way to the next point.
