### ISSUE TITLE
Few bugs/issues

### ISSUE THREAD

**Issue by wetdragon** [tanjeffreyz/auto-maple#72]
Noticed a few things from using this for a few hours `v2.2.0` 

- Shadowy elite mobs, darkness debuff triggers alert and stops everything 
( pretty sure it does not cover the mini map, but probly affects with how it gets detected somehow ? )
![alt text](https://i.imgur.com/IASuow1.png) ![alt text](https://i.imgur.com/23sqe04.png) 

- the player gets stuck a lot on the sides of maps if knocked off/down ( stuck jumping for a bit in 1 spot, Its trying to go from the bottom/right to the top/right directly on mts3 without moving a bit to the left first ) 
- accidently enters left/right portals sometimes ( happened 2-3 times within 6-8hours ish~, so its not that common )
^could maybe try to press up and attempt to get back into the map intended map when/if this happens ? assuming the player don't get knocked around and can't get back ofc. or maybe disable the "up" key from being used around portals ?

- Wolf / Pollo and Fritto portals keep the npc window open if they get accidently triggered, some way to auto close these ?
- Use some pet food after completing a rune, for ppl that don't have auto pet feed
(think this would be a convenient way to include it outside of the command book without it getting spammed to often)

- Notification/small alert for runes Being on the map, warning alert if the rune has not been completed after X seconds 
( think this would be nice even if it works just in case it breaks for some reason or if it can't get solved after few attempts due to getting knocked around ) 

- had the surprise mission appear in front of the map, this broke the detection so maybe someway to auto close it?
![alt text](https://i.imgur.com/DpY0b4t.png)

**`Im using a amd gpu / aka no cuda. but think these issues apply even if you have a nvidia/cuda`**

**Comment by tanjeffreyz** [comment]
Hi, thanks a lot for the detailed bug-list! The newest release should address some of these issues (notably the darkness bug and clicking on rune buffs), the others I'm still working on!

**Comment by takimc** [comment]
Hello. There is an indirect but very easy way to solve the problem of disarming the rune. It is to enter the point store.
If you use this method, you can deal with rotating runes, blue or purple runes, and you do not need to sound an alert. (You can also unlock blue runes if you use a method that doesn't use machine learning, but it's not the smartest way)

**Comment by pmw1446** [comment]
> 여보세요. 룬 해결 문제와 관련하여 간접적이지만 매우 쉬운 방법이 있습니다. 포인트 스토어에 입장하는 것입니다. 이 방법을 사용하면 회전하는 룬, 파란색 또는 보라색 룬을 처리할 수 있으며 경보를 울릴 필요가 없습니다. (머신러닝을 사용하지 않는 방법을 사용한다면 블루룬도 잠금 해제할 수 있지만 가장 똑똑한 방법은 아닙니다)

what is a point store?

**Comment by takimc** [comment]
> > 여보세요。룬해결문제와관련하여간접적이zippy만매우쉬운방법이있습니다。포인트cosplay토어에입장하는것입니다。이방법을사용하면회전하는룬、파란색또는보라색룬을처리할수있있 （머신러닝을사용하zippy않는방법을사용한다면블루룬도잠금해제할수있
> 
> ポイントストアとは何ですか？

Cash Shop

**Comment by ScottBouloutian** [comment]
I have also noticed an issue with rotating runes, the Cash Shop method sounds cool, will have to try it. I suspect some of the issues you are seeing with the ms3 routine may come from the fact that it is out of date. For example, it still uses goto command which I believe are no longer used. I think it has to be updated to the newer routine syntax.
