### ISSUE TITLE
Rune "Danger" Alert not working

### ISSUE THREAD

**Issue by Nekololizu** [tanjeffreyz/auto-maple#88]
"Added sound notifications for runes, "danger" alert occurs after 4.5 minutes (slightly before the elite boss curse begins)"

^after failing a rune several times in a row and getting down to the 50% curse the danger alert still didn't trigger, it only kept playing the rune notification after each failed rune attempt so think it might be resetting the timer every time ? I didn't time it but at least assuming "elite boss curse begins" meant before the meso/exp reduction start?

**Comment by tanjeffreyz** [comment]
Fixed!
