### ISSUE TITLE
Rune solving attempts while far away

### ISSUE THREAD

**Issue by wetdragon** [tanjeffreyz/auto-maple#91]
If positions are really close to each other it won't walk to runes properly sometimes
for example clp where platforms are really close together
![python_j06pJPamLf](https://user-images.githubusercontent.com/16899482/170844908-901684ea-5177-4429-bf70-eed547b755d0.png)
^it tried to start solving the rune from here while being under it, jumping up from the bottom to the middle but not from the middle to the top after that
 (its technically within the runes range position wise, but the player is not nearby the rune)

maybe positions could have different sizes to be more/less precise to avoid issues with small platforms or platforms being close?
while keeping the current size as default

**Comment by cheezeburger** [comment]
I had the same issue but I resolved it by making the platform Y coordinate higher

**Comment by ScottBouloutian** [comment]
You talked about positions having different sizes; I think this might currently exist. I saw some settings like `move_tolerance` and `adjust_tolerance` which I think give you control over the radius of those red circles.
